import { Injectable } from '@angular/core';
import { Movie } from '../models/movie.interface';

@Injectable({
  providedIn: 'root',
})
export class MovieService {
  private movies: Movie[] = [
    // Sci-Fi
    {
      id: 1,
      title: 'Inception',
      synopsis: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
      year: 2010,
      rating: 8.8,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/YoHD9XEInc0',
      trending: true,
      views: 15420,
    },
    {
      id: 3,
      title: 'Interstellar',
      synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      imageUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
      year: 2014,
      rating: 8.6,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/zSWdZVtXT7E',
      trending: true,
      views: 12300,
    },
    {
      id: 5,
      title: 'The Matrix',
      synopsis: 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
      year: 1999,
      rating: 8.7,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/vKQi3bBA1y8',
      views: 18900,
    },
    {
      id: 15,
      title: 'Blade Runner 2049',
      synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
      imageUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
      year: 2017,
      rating: 8.0,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/gCcx85zbxz4',
      views: 8700,
    },
    {
      id: 16,
      title: 'Arrival',
      synopsis: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
      year: 2016,
      rating: 7.9,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/tFMo3UJ4B4g',
      views: 6500,
    },
    {
      id: 17,
      title: 'Dune',
      synopsis: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
      year: 2021,
      rating: 8.0,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/n9xhJrPXop4',
      trending: true,
      views: 14200,
    },
    {
      id: 18,
      title: 'Ex Machina',
      synopsis: 'A young programmer is selected to participate in a groundbreaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/btbRB7BrD887j5NcUwcTz5UM8gg.jpg',
      year: 2014,
      rating: 7.7,
      genre: 'Sci-Fi',
      trailerUrl: 'https://www.youtube.com/embed/EoQuVnKhxaM',
      views: 5400,
    },
    // Action
    {
      id: 2,
      title: 'The Dark Knight',
      synopsis: 'When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nMceA.jpg',
      year: 2008,
      rating: 9.0,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY',
      trending: true,
      views: 22100,
    },
    {
      id: 7,
      title: 'Gladiator',
      synopsis: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgpSuf.jpg',
      year: 2000,
      rating: 8.5,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/owK1qxDselE',
      views: 11200,
    },
    {
      id: 11,
      title: 'John Wick',
      synopsis: 'An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
      year: 2014,
      rating: 7.4,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/C0BMx-qxsP4',
      views: 9800,
    },
    {
      id: 19,
      title: 'Mad Max: Fury Road',
      synopsis: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a drifter named Max.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
      year: 2015,
      rating: 8.1,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/hEJnMQG9ev8',
      trending: true,
      views: 13500,
    },
    {
      id: 20,
      title: 'Die Hard',
      synopsis: 'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg',
      year: 1988,
      rating: 8.2,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/jaJuwKCmJbY',
      views: 10400,
    },
    {
      id: 21,
      title: 'Top Gun: Maverick',
      synopsis: 'After thirty years of service, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DG3zsA1.jpg',
      year: 2022,
      rating: 8.3,
      genre: 'Action',
      trailerUrl: 'https://www.youtube.com/embed/giXco2jaZ_4',
      trending: true,
      views: 16700,
    },
    // Drama
    {
      id: 6,
      title: 'Fight Club',
      synopsis: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
      year: 1999,
      rating: 8.8,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/qtRKdVHc-cE',
      views: 14300,
    },
    {
      id: 8,
      title: 'The Shawshank Redemption',
      synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/9cjIGRQL9wkgpZO1fireUe7LTEb.jpg',
      year: 1994,
      rating: 9.3,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/6hB3S9d6u0Q',
      trending: true,
      views: 25600,
    },
    {
      id: 9,
      title: 'Forrest Gump',
      synopsis: 'The presidencies of Kennedy and Johnson, the Vietnam War and other events unfold from the perspective of an Alabama man with a low IQ.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
      year: 1994,
      rating: 8.8,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/bLvqoHBptjg',
      views: 19800,
    },
    {
      id: 22,
      title: 'The Green Mile',
      synopsis: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
      year: 1999,
      rating: 8.6,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/Ki4haFrqSrw',
      views: 11800,
    },
    {
      id: 23,
      title: 'Schindler\'s List',
      synopsis: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      year: 1993,
      rating: 9.0,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/gG22XNhtnoY',
      views: 13200,
    },
    {
      id: 24,
      title: 'Whiplash',
      synopsis: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
      year: 2014,
      rating: 8.5,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/7d_jQycdQGo',
      views: 8900,
    },
    {
      id: 25,
      title: 'The Prestige',
      synopsis: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg',
      year: 2006,
      rating: 8.5,
      genre: 'Drama',
      trailerUrl: 'https://www.youtube.com/embed/o4gHCmTQDVI',
      views: 7600,
    },
    // Crime
    {
      id: 4,
      title: 'Pulp Fiction',
      synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
      year: 1994,
      rating: 8.9,
      genre: 'Crime',
      trailerUrl: 'https://www.youtube.com/embed/s7EdQ4FqbhY',
      views: 17200,
    },
    {
      id: 10,
      title: 'The Godfather',
      synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      year: 1972,
      rating: 9.2,
      genre: 'Crime',
      trailerUrl: 'https://www.youtube.com/embed/sY1S34973zA',
      trending: true,
      views: 24500,
    },
    {
      id: 14,
      title: 'Goodfellas',
      synopsis: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his partners Jimmy Conway and Tommy DeVito.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
      year: 1990,
      rating: 8.7,
      genre: 'Crime',
      trailerUrl: 'https://www.youtube.com/embed/qo5jJpHtI1Y',
      views: 12600,
    },
    {
      id: 26,
      title: 'The Departed',
      synopsis: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
      year: 2006,
      rating: 8.5,
      genre: 'Crime',
      trailerUrl: 'https://www.youtube.com/embed/iojhqm0JTW4',
      views: 9300,
    },
    {
      id: 27,
      title: 'City of God',
      synopsis: 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a drug dealer.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2TfC.jpg',
      year: 2002,
      rating: 8.6,
      genre: 'Crime',
      trailerUrl: 'https://www.youtube.com/embed/dcUOO4Itgmw',
      views: 7800,
    },
    // Thriller
    {
      id: 12,
      title: 'Parasite',
      synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      year: 2019,
      rating: 8.5,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/5xH0HfJHsaY',
      trending: true,
      views: 16800,
    },
    {
      id: 13,
      title: 'Se7en',
      synopsis: 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg',
      year: 1995,
      rating: 8.6,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/znmZoVkCjpI',
      views: 11500,
    },
    {
      id: 28,
      title: 'Zodiac',
      synopsis: 'Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/q2DNRMP72VnF3FMbcCAO8LJL5bV.jpg',
      year: 2007,
      rating: 7.7,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/yNncHPl1UXg',
      views: 6200,
    },
    {
      id: 29,
      title: 'Gone Girl',
      synopsis: 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected he may not be innocent.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/qymaJhZ0IKJn3KCVO0z06xgF600.jpg',
      year: 2014,
      rating: 8.1,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/2-_-1nJf8Vg',
      views: 9100,
    },
    {
      id: 30,
      title: 'Shutter Island',
      synopsis: 'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/kve20tXMHZONoKyEh18tVWBsvPR.jpg',
      year: 2010,
      rating: 8.2,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/5iaYLCiq5RM',
      views: 10700,
    },
    {
      id: 31,
      title: 'The Silence of the Lambs',
      synopsis: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/uS9m8OBk1RVFDUGBbXACRhYv0CE.jpg',
      year: 1991,
      rating: 8.6,
      genre: 'Thriller',
      trailerUrl: 'https://www.youtube.com/embed/W6GDil0rGls',
      views: 13900,
    },
    // Horror
    {
      id: 32,
      title: 'The Shining',
      synopsis: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg',
      year: 1980,
      rating: 8.4,
      genre: 'Horror',
      trailerUrl: 'https://www.youtube.com/embed/5Cb3ik6zP2I',
      views: 14100,
    },
    {
      id: 33,
      title: 'Get Out',
      synopsis: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/qbaERiTsJMnlOGz0sSCRHVJsn54.jpg',
      year: 2017,
      rating: 7.7,
      genre: 'Horror',
      trailerUrl: 'https://www.youtube.com/embed/DzfpyUB60YY',
      trending: true,
      views: 11600,
    },
    {
      id: 34,
      title: 'Hereditary',
      synopsis: 'A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/p9fmuz2Oj3KOSwxAOnELkiGrsT6.jpg',
      year: 2018,
      rating: 7.3,
      genre: 'Horror',
      trailerUrl: 'https://www.youtube.com/embed/V6wWKNij_1M',
      views: 7400,
    },
    {
      id: 35,
      title: 'Alien',
      synopsis: 'After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
      year: 1979,
      rating: 8.5,
      genre: 'Horror',
      trailerUrl: 'https://www.youtube.com/embed/LjLamj-b0I8',
      views: 15800,
    },
    // Comedy
    {
      id: 36,
      title: 'The Grand Budapest Hotel',
      synopsis: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
      year: 2014,
      rating: 8.1,
      genre: 'Comedy',
      trailerUrl: 'https://www.youtube.com/embed/1Fg5iWmQjwk',
      views: 8200,
    },
    {
      id: 37,
      title: 'Superbad',
      synopsis: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg',
      year: 2007,
      rating: 7.6,
      genre: 'Comedy',
      trailerUrl: 'https://www.youtube.com/embed/4eaZ_48ZYog',
      views: 7900,
    },
    {
      id: 38,
      title: 'The Big Lebowski',
      synopsis: 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and gets tangled in a kidnapping scheme.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/fMBjKDKjSZqbnLxE0sTEdy28WGO.jpg',
      year: 1998,
      rating: 8.1,
      genre: 'Comedy',
      trailerUrl: 'https://www.youtube.com/embed/cd-go0oBF4Y',
      views: 9500,
    },
    {
      id: 39,
      title: 'Knives Out',
      synopsis: 'A detective investigates the death of the patriarch of an eccentric, combative family, where everyone is a suspect.',
      imageUrl: 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
      year: 2019,
      rating: 7.9,
      genre: 'Comedy',
      trailerUrl: 'https://www.youtube.com/embed/qGqiHJTsRkQ',
      trending: true,
      views: 10300,
    },
  ];

  getMovies(): Movie[] {
    return this.movies;
  }

  getMovieById(id: number): Movie | undefined {
    return this.movies.find((m) => m.id === id);
  }

  getGenres(): string[] {
    return [...new Set(this.movies.map((m) => m.genre))];
  }

  getMoviesByGenre(genre: string): Movie[] {
    return this.movies.filter((m) => m.genre === genre);
  }

  getFeaturedMovies(): Movie[] {
    return this.movies.filter((m) => m.trending);
  }

  getTrendingMovies(): Movie[] {
    return this.movies
      .filter((m) => m.trending)
      .sort((a, b) => (b.views || 0) - (a.views || 0));
  }

  searchMovies(query: string): Movie[] {
    const q = query.toLowerCase();
    return this.movies.filter(
      (m) =>
        m.title.toLowerCase().includes(q) ||
        m.genre.toLowerCase().includes(q) ||
        m.synopsis.toLowerCase().includes(q)
    );
  }

  getRelatedMovies(movie: Movie): Movie[] {
    return this.movies
      .filter((m) => m.genre === movie.genre && m.id !== movie.id)
      .slice(0, 6);
  }
}
